### PR TITLE
Add guidance on how to set up Azure 2-factor auth

### PR DESCRIPTION
**Pull request by lawrence-forooghian**
I’m not yet sure where we’ll link to this from, but probably either
internal dxw documentation, or the onboarding checklist that we’ll make
for the product owner.

### CODE REVIEW

**Comment by lawrence-forooghian** [comment]
[As a first-line support developer I want to be able to set up Azure 2FA without sharing a phone number](https://trello.com/c/03jbdYQq/1456-as-a-first-line-support-developer-i-want-to-be-able-to-set-up-azure-2fa-without-sharing-a-phone-number)

**Comment by lawrence-forooghian** [comment]
Well, whatever I did, I now can't log in to Azure. So maybe it was wrong.

**Comment by lawrence-forooghian** [comment]
OK, I think it was a problem in how I changed the 2FA settings. There are two AD orgs, one for DfE Platform Identity and one for digital.education.gov.uk and they’ve each got their own 2FA settings. I changed the wrong one the first time. I've asked Lee to test out these instructions whenever he gets invited to Azure.

**Comment by leedxw** [comment]
These instructions worked for me.

**Pull request merged**
