### PR TITLE
removed dqt_client_port from container build

### PR DESCRIPTION
**Pull request by and-lucas-kelly**

### CODE REVIEW

**Comment by nomasprime** [comment]
Think there might have been a misunderstanding on Friday. Don't think we need to remove this, doesn't it work as expected with `nil`?

**Comment by and-lucas-kelly** [comment]
You can't have a null vale in Key Vault and i'm not sure how it would behave if we added nil as the value. Will the port number not always be set in the code?

**Comment by nomasprime** [comment]
Didn't we already demonstrate it as working with no value?

**Review by nomasprime — APPROVED** [review]
Doesn't look like the right fix but, given limited support during release week, I'll approve on faith that it's a fix, at least for now.

**Pull request merged**
